# Generated by Django 3.2.18 on 2023-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d'),
        ),
    ]
