# Generated by Django 3.2.18 on 2023-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230522_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_img',
            field=models.ImageField(default='default_background.jpg', null=True, upload_to='background_img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='default_profile.png', null=True, upload_to='profile_img/%Y/%m/%d'),
        ),
    ]
