# Generated by Django 3.2.18 on 2023-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_key',
            field=models.TextField(null=True),
        ),
    ]
